name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41ec0c3d359558c4515180560a45882126263852e0d7a4c2ed2c1031be84cf5f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
