name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d85c726f14451c1b1d411d51dec01acebf65809801a1723ada0ca1c695b2f5f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
