name = "Performant Pack"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5e6dfcc7d52fcca71f1f9a0b185014e37198b6fef7bc589d160c5cdd6e0c426"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
