name = "Performant Pack"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcc196d0773871976428587ec4d428ac59de32a79f34b7c4ddfa7c2868ecda2f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
