name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dd4af693421b986b8f5c0f36b72909f242abc3a9cdf1eccb984ef309e6d7997"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
