name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98848c93dfa5c1e72652943ac7818b89486be5ce422af41458f5f2ba54ea98ce"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
