name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa032212c1c9789b22c280b1fee66fe1fbc57ec6424e0902718d0c898578189b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
