name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c733155b05a7a8821da66d181869a1d586762a3e940c3c13b5eaae868a26f9c"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
