name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7f04fda937a342f10fc1f97e2ae010e4839c5c2e6b733ec58903385394c0142"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
