name = "Performant Pack"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6120633305b862c5cb8cc7655270e43550738199ad260ff266e151c93e6d0392"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
