name = "Performant Pack"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a40d1f5f59030fa65d71c47070798681201c72130b73d4e581ab561e4f53028"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
