name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c64bf8989e5fbb6baf999a658bdfdad18a6c25e6946959db04d87bc2254cdff"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
