name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79ec3d615aa5306493a709329a017f9b9802851763ea7a5e16956a002b6e97f3"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
