name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d391dda2d6ff8d8528070247003228542beb9cc85c8c0ddb944e5082eb9abff8"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
