name = "Performant Pack"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61770baa0bdf4a0cc05a182c65e7ce81b8e4c5007bf7b38fa6ec41e516a70729"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
