name = "Performant Pack"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecac49e594510c45a9ee92d0fd0ece8e59de82890072e27bb5ce53a0c388c18d"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
