name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16fc49f496ece4dc140cb63c7dc587a34da0adfc5ae64b32ee7cf96778883860"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
