name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a98f865e343e1ea0ef02c5277a75b943f9c32ce38c708ceac3e3a64a0cd5a5b0"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
