name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd95c5eb351f98f75bc952d17c1edd79e34858d3bc1f55a512ff171eec4f8331"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
