name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd27010ba814e09b7b28e39023176e1c4b7b1e9bbf994a814373ecbd9f8d1890"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
