name = "Performant Pack"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daea2d4c07f96216549f43c24a2bfc22b66a99759212df4031baa228c1a11378"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
