name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a01bdd79feb171f33ccbc6b0057c59e92208168ce13191770a218c0f7dd52655"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
