name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efa7cfdc6b150fd9f8c42845ae6118cbf0452a6f03941c488c8b476e6ef19ee7"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
