name = "Performant Pack"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9badf08a265fb7a2f9b3fa2ad82d01d3ff109eb0d3db0b7713f00937d9b746e"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
