name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dd00bcc39b648a0ba71b50fecc852cb75ad691989e21c1daa10e6acc02873b0"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
