name = "Shipping Container SMP"
author = "ssamjh"
version = "1.19.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d08ca810de70211d6c8601aaed1ee8d48002083fd17db4eab308334107161576"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
